import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv[2] === 'production';

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  logLevel: "info",
  sourcemap: isProduction ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
};

// Build for production
if (isProduction) {
  try {
    await esbuild.build(buildOptions);
    console.log('Build completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
} 
// Development build with watch
else {
  const ctx = await esbuild.context(buildOptions);
  
  // Watch for changes
  await ctx.watch();
  
  // Start a development server
  const { host, port } = await ctx.serve({
    servedir: '.',
    port: 3000
  });
  
  console.log(`Watching for changes...`);
  console.log(`Serving at http://${host}:${port}`);
}
